### ISSUE TITLE
bbox content in rotaed box task coco file

### ISSUE THREAD

**Issue by qgh1223** [LUCKMOONLIGHT/SLRDet#1]
I want to know the meaning of every parameter in bbox in ODAI coco file.Is it centerx,centery,rotated box width,height,angle?

**Comment by qgh1223** [comment]
The range of angle?

**Comment by LUCKMOONLIGHT** [comment]
yeah. angle period is [-90 ~ 90]

**Comment by qgh1223** [comment]
I get the bbox value from opencv minAreaRect function and parameter is all points' coordinate.Is it right?Thank you for your reply
