### ISSUE TITLE
请问为何报错了？

### ISSUE THREAD

**Issue by tiber2013** [LUCKMOONLIGHT/SLRDet#3]
![图片](https://user-images.githubusercontent.com/25317136/71089623-40afb480-21dc-11ea-83c9-8b00b9a93f54.png)
myconfig/下的rotated_retinanet_r101_fpn_1x.py就会报错，retinanet_x101_64x4d_fpn_1x.py不报错。

**Comment by LUCKMOONLIGHT** [comment]
请对比一下这两个文档的不同，出现这个问题的原因是由于syncbn导致的

**Comment by tiber2013** [comment]
非常感谢老师！我把所有SyncBN都替换了，然后删掉build重新setup.py 和setup_rotated.py就可以了。
